# Generated by Django 4.0.5 on 2022-06-16 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notifcation_house_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifcation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
