# Generated by Django 4.0.5 on 2022-06-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercompliant',
            old_name='house_no',
            new_name='user',
        ),
    ]
