# Generated by Django 4.0.5 on 2022-06-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_rename_house_no_usercompliant_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercompliant',
            old_name='user',
            new_name='user_id',
        ),
    ]
