# Generated by Django 4.0.5 on 2022-06-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffAccount', '0002_alter_staffaccount_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
