# Generated by Django 4.0.5 on 2022-06-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StaffAccount', '0004_alter_staffaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffaccount',
            options={},
        ),
        migrations.AlterModelManagers(
            name='staffaccount',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='username',
        ),
    ]
