# Generated by Django 4.0.5 on 2022-06-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffAccount', '0005_alter_staffaccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=50)),
            ],
        ),
    ]
