# Generated by Django 4.0.5 on 2022-06-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffAccount', '0006_rolesstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='is_change',
            field=models.BooleanField(default=False),
        ),
    ]
