# Generated by Django 4.0.5 on 2022-06-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffAccount', '0007_staffaccount_is_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='role',
            field=models.IntegerField(max_length=30),
        ),
    ]
