# Generated by Django 4.0.5 on 2022-06-15 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StaffAccount', '0008_alter_staffaccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaffAccount.rolesstaff'),
        ),
    ]
