# Generated by Django 4.0.5 on 2022-06-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffAccount', '0009_alter_staffaccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
