# Generated by Django 4.0.5 on 2022-06-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffAccount', '0010_alter_staffaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesstaff',
            name='rolename',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
