# Generated by Django 4.0.5 on 2022-06-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
