# Generated by Django 4.0.5 on 2022-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_password_change_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='house_no',
            field=models.CharField(max_length=200),
        ),
    ]
